### PR TITLE
Use TCP instead of PIPES on Windows

### PR DESCRIPTION
**Pull request by deathaxe**
With "oop_mode": "PIPE" ST fails to connect to the codeintel oop server with WinError 109. Using "tcp" works fine.

Therefore a SublimeCodeIntel (Windows).sublime-settings file may be added overriding this setting for Windows only.

### CODE REVIEW

**Comment by Kronuz** [comment]
Is this the only issue with Windows and the latest beta? (Beta 36)?

**Comment by deathaxe** [comment]
Looks like this on a first glance. The latest built starts the codeintel server hidden on Windows and completions work. I tested with XML and python, but guess the others do so, too.

But your settings structure seems to need the whole settings file to be copied to _SublimeCodeIntel (Windows).sublime-settings_ with the one value being modified.

I recently encountered the following traceback, but was not quite sure how I triggered it. Seems not to be Windows related.

```
Traceback (most recent call last):
  File "C:\Apps\Sublime\sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "C:\Apps\Sublime\Data\Packages\SublimeCodeIntel\settings.py", line 212, in run
    self.settings.save()
  File "C:\Apps\Sublime\Data\Packages\SublimeCodeIntel\settings.py", line 153, in save
    view.run_command('settings_view_editor', self)
  File "C:\Apps\Sublime\sublime.py", line 838, in run_command
    sublime_api.view_run_command(self.view_id, cmd, args)
TypeError: Value required
```

**Comment by Kronuz** [comment]
How come is the pipes mode failing. Supposedly it should work... does it have to do with this: https://www.digitalenginesoftware.com/blog/archives/47-Passing-pipes-to-subprocesses-in-Python-in-Windows.html

**Comment by deathaxe** [comment]
Using pipes results in the `codeintel` process being started repetitively and failing with following errors:

```
Error reading data from OOP CodeIntel: Type str doesn't support the buffer API
Error reading data from OOP CodeIntel: Type str doesn't support the buffer API
Error reading data from OOP CodeIntel: Type str doesn't support the buffer API
Error reading data from OOP CodeIntel: Type str doesn't support the buffer API
Error reading data from OOP CodeIntel: Type str doesn't support the buffer API
Error reading data from OOP CodeIntel: Type str doesn't support the buffer API
Error reading data from OOP CodeIntel: Type str doesn't support the buffer API
Error reading data from OOP CodeIntel: [WinError 109] Die Pipe wurde beendet.
Error reading data from OOP CodeIntel: Type str doesn't support the buffer API
Error reading data from OOP CodeIntel: Type str doesn't support the buffer API
```

Hmm. With a second thought about it it seems not to be a pipe issue itself.

Maybe just an unproper way of using `str` somewhere?

**Comment by Kronuz** [comment]
Problem was not with Windows pipes, something else was wrong. Should be fixed in v3.0.0-beta.38. Note you will also need to upgrade CodeIntel to v2.0.0-beta.35 (`pip install -U --pre CodeIntel`)

**Pull request closed without merging**
