### PR TITLE
fix codeintel_scan_exclude_dir for JavaScript / add support for PHP

### PR DESCRIPTION
**Pull request by wizza-smile**
I added codeintel_scan_exclude_dir support for PHP to reduce the number of import dirs

### CODE REVIEW

**Comment by Kronuz** [comment]
It'd be great if this could be split in several pull requests going to the https://github.com/SublimeCodeIntel/CodeIntelSources/src repositories instead of to this repository (which is for releases only)

**Comment by wizza-smile** [comment]
we are all waiting for the release, mr skinner jr!

**Comment by Kronuz** [comment]
I'm working in a release now, finally.

@wizza-smile, There are many great things in your fork. I'll cherry pick them and maybe later we could have a chat as I have a few questions. Do you use irc? gmail?

**Comment by wizza-smile** [comment]
god, I love open-source. go ahead!

**Comment by Kronuz** [comment]
Thank you so much @wizza-smile, I'm releasing v2.1.0 (compatible with ST2 and ST3).

I'm still working in updating the Komodo baseline (which will become v3.0), if anyone is interested in contributing, please contact me. I really need help maintaining the project.

**Pull request closed without merging**
